from pydantic import BaseModel, Field


class NegotiationProposal(BaseModel):
    """
    Proposal generated by a negotiating agent.

    Every participant (Retailer, Distributor, Factory) returns this schema.
    """

    reasoning: str = Field(
        description="Reasoning behind the proposal."
    )

    accepted: bool = Field(
        description="Whether the previous proposal is accepted."
    )

    proposed_quantity: int = Field(
        ge=0,
        description="Quantity proposed."
    )

    constraints: list[str] = Field(
        default_factory=list,
        description="Constraints affecting this proposal."
    )

    comments: str = Field(
        default="",
        description="Additional negotiation comments."
    )


class NegotiationTurn(BaseModel):
    """
    One proposal made during a negotiation.
    """

    round_number: int
    proposer: str
    proposal: NegotiationProposal


class NegotiationResult(BaseModel):
    """
    Final outcome of a bilateral negotiation.
    """

    success: bool
    agreed_quantity: int
    turns: list[NegotiationTurn]
    total_rounds: int
    final_message: str = ""
